[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "flask db upgrade && gunicorn app:app"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicy = "on-failure:10"

[env]
PYTHON_VERSION = "3.11" 