[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "flask db upgrade && gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicy = "on-failure:10"

[env]
PYTHON_VERSION = "3.11" 