services:
  - type: web
    name: golf-simulator-directory
    env: python
    buildCommand: |
      pip install -r requirements.txt
      # Wait for database to be ready
      sleep 10
      # Initialize database schema and migrations
      export FLASK_APP=app.py
      # Create database tables
      python -c "from app import db, app; db.init_app(app); app.app_context().push(); db.create_all()"
      # Clean up any existing migrations
      rm -rf migrations
      # Initialize fresh migrations
      flask db init || true
      flask db migrate -m "initial migration" || true
      flask db upgrade || true
      # Sync with Google Sheet with retries
      for i in {1..3}; do
        echo "Attempt $i to sync with Google Sheet..."
        flask sync-sheet && break || { echo "Sync failed, waiting before retry..."; sleep 5; }
      done
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_SHEET_URL
        value: https://docs.google.com/spreadsheets/d/e/2PACX-1vQ7Zfd9J7uhAhKoHLfqWrjnOVqjGvK9YQVZNFe4CjnQDGqRDi_HHf_ys4fJMmborCNKYxpwqrQHx2QF/pub?output=csv
      - key: DATABASE_URL
        fromDatabase:
          name: golf-simulator-db
          property: connectionString

databases:
  - name: golf-simulator-db
    databaseName: golf_simulators
    plan: free 