services:
  - type: web
    name: golf-simulator-directory
    env: python
    buildCommand: |
      pip install -r requirements.txt
      pip install python-slugify
      # Wait for database to be ready
      sleep 10
      # Initialize database schema and migrations
      export FLASK_APP=app.py
      python -c "from app import db; from app import app; with app.app_context(): db.create_all()"
      # Clean up any existing migrations
      rm -rf migrations
      # Initialize fresh migrations
      flask db init
      flask db migrate -m "initial migration"
      flask db upgrade
      # Import data
      python import_data.py
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: golf-simulator-db
          property: connectionString

databases:
  - name: golf-simulator-db
    databaseName: golf_simulators
    plan: free 