"""Add membership_info column

Revision ID: 198cdfc78515
Revises: 
Create Date: 2025-02-17 21:17:59.955695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '198cdfc78515'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('membership_info', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('membership_info')

    # ### end Alembic commands ###
