"""Add last_synced_at column

Revision ID: 1e979bf1a76c
Revises: 198cdfc78515
Create Date: 2025-02-17 21:58:34.035026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e979bf1a76c'
down_revision = '198cdfc78515'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_synced_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('last_synced_at')

    # ### end Alembic commands ###
